# Generated by Django 4.0.3 on 2022-03-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('designation', models.TextField()),
                ('address', models.TextField(max_length=255)),
                ('mobile', models.IntegerField()),
                ('emaill', models.TextField()),
                ('gender', models.CharField(max_length=255)),
                ('Qualification', models.CharField(max_length=255)),
            ],
        ),
    ]
