# Generated by Django 4.0.3 on 2022-03-31 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='designation',
        ),
    ]
